"groups":
- "name": "argo-workflows"
  "rules":
  - "alert": "ArgoWorkflowsHighWorkflowFailureRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-workflows-overview-skj2/argo-workflows-overview?var-namespace={{ $labels.namespace }}"
      "description": "More than 10% of workflows are failing or erroring in {{ $labels.namespace }} the past 5m."
      "summary": "Argo Workflows high workflow failure rate."
    "expr": |
      (
        sum(
          rate(
            argo_workflows_total_count{
              job=~".*",
              phase=~"Failed|Error"
            }[5m]
          )
        ) by (cluster, namespace)
        /
        sum(
          rate(
            argo_workflows_total_count{
              job=~".*"
            }[5m]
          )
        ) by (cluster, namespace)
        * 100
      ) > 10
    "for": "1m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoWorkflowsPendingWorkflows"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-workflows-overview-skj2/argo-workflows-overview?var-namespace={{ $labels.namespace }}"
      "description": "More than 5 workflows are pending in {{ $labels.namespace }} for the past 15m."
      "summary": "Argo Workflows has many pending workflows."
    "expr": |
      sum(
        argo_workflows_gauge{
          job=~".*",
          phase="Pending"
        }
      ) by (cluster, namespace)
      > 5
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoWorkflowsControllerHighErrorRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-workflows-controller-skj2/argo-workflows-controller"
      "description": "More than 5 errors per second with cause {{ $labels.cause }} the past 5m."
      "summary": "Argo Workflows controller has a high error rate."
    "expr": |
      sum(
        rate(
          argo_workflows_error_count{
            job=~".*"
          }[5m]
        )
      ) by (cluster, cause)
      > 5
    "for": "1m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoWorkflowsQueueDepthHigh"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-workflows-controller-skj2/argo-workflows-controller"
      "description": "Queue {{ $labels.queue_name }} has a depth of more than 100 for the past 5m."
      "summary": "Argo Workflows controller queue depth is high."
    "expr": |
      sum(
        argo_workflows_queue_depth_gauge{
          job=~".*"
        }
      ) by (cluster, queue_name)
      > 100
    "for": "5m"
    "labels":
      "severity": "warning"
